name: Update requirements.txt

# runs every day at midnight UTC
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Upload the original requirements.txt
      - name: Upload old requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: old-requirements
          path: requirements.txt

      # Set up Python & venv
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate venv and upgrade pip
        run: |
          source .venv/bin/activate
          pip install --upgrade pip

      # Upgrade discord.py, internetarchive & python-dotenv
      - name: Upgrade discord.py, internetarchive & python-dotenv
        run: |
          source .venv/bin/activate
          pip install --upgrade discord.py internetarchive python-dotenv

      # Rewrite requirements.txt with those packages
      - name: Write packages to requirements.txt
        run: |
          source .venv/bin/activate
          pip freeze \
            | grep -E '^(discord\.py|internetarchive|python-dotenv)==' \
            > requirements.txt

      # Upload the updated requirements.txt
      - name: Upload updated requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: updated-requirements
          path: requirements.txt

      # Commit & push if anything changed
      - name: Commit & push updated requirements
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          if git diff --cached --quiet; then
            echo "No changes to requirements.txt"
          else
            git commit -m "keep requirements.txt up to date"
            git push
          fi
